# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ListRequest" do
    optional :title, :string, 1
  end
  add_message "Task" do
    optional :title, :string, 1
    optional :description, :string, 2
  end
  add_message "Tasks" do
    repeated :tasks, :message, 1, "Task"
  end
end

ListRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("ListRequest").msgclass
Task = Google::Protobuf::DescriptorPool.generated_pool.lookup("Task").msgclass
Tasks = Google::Protobuf::DescriptorPool.generated_pool.lookup("Tasks").msgclass
