# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo.proto for package ''

require 'grpc'
require 'todo'

module Todo

  # TODO: add proto service documentation here
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Todo'

    rpc :AddTask, Task, Task
    rpc :ListTasks, ListRequest, Tasks
  end

  Stub = Service.rpc_stub_class
end
